apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  nvIpam:
    image: nvidia-k8s-ipam
    repository: $NVIDIA_IPAM_REPOSITORY
    version: $NVIDIA_IPAM_VERSION
    enableWebhook: false
  secondaryNetwork:
    cniPlugins:
      image: plugins
      repository: $CNI_PLUGINS_REPOSITORY
      version: $CNI_PLUGINS_VERSION
    multus:
      image: multus-cni
      repository: $MULTUS_REPOSITORY
      version: $MULTUS_VERSION
