apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  sriovDevicePlugin:
    image: sriov-network-device-plugin
    repository: $SRIOVNETOP_SRIOV_DEVICE_PLUGIN_REPOSITORY
    version: $SRIOVNETOP_SRIOV_DEVICE_PLUGIN_VERSION
    config: |
      {
        "resourceList": [
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "hostdev",
            "selectors": {
              "vendors": ["15b3"],
              "isRdma": true
            }
          }
        ]
      }
  nvIpam:
    image: nvidia-k8s-ipam
    repository: $NVIDIA_IPAM_REPOSITORY
    version: $NVIDIA_IPAM_VERSION
    imagePullSecrets: []
    enableWebhook: false
  secondaryNetwork:
    cniPlugins:
      image: plugins
      repository: $CNI_PLUGINS_REPOSITORY
      version: $CNI_PLUGINS_VERSION
    multus:
      image: multus-cni
      repository: $MULTUS_REPOSITORY
      version: $MULTUS_VERSION