[repo]
logging = "warn"


[repo_docs]
enabled = true
docs_root = "docs"
project = "nvidia_network_operator"
name = "NVIDIA Network Operator"
version = "v24.10.0"
copyright_start = 2024
social_media_set = []
social_media = []
favicon = "${root}/assets/favicon.ico"
logo = "${root}/assets/nvidia-logo-white.png"
extensions_extra = ['sphinx_substitution_extensions']

[repo_docs.builds.linkcheck]
build_by_default = false
output_format = "linkcheck"
