[repo]
logging = "warn"


[repo_docs]
enabled = true
docs_root = "docs"
project = "nvidia_network_operator"
name = "NVIDIA Network Operator"
version = "0.1.0"
copyright_start = 2024
social_media_set = []
social_media = []
favicon = "${root}/assets/favicon.ico"
logo = "${root}/assets/nvidia-logo-white.png"