FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
        make curl git \
        python3 python3-pip python3-venv \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
