apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  ofedDriver:
    image: doca-driver
    repository: nvcr.io/nvidia/mellanox
    version: |doca-driver-version|
  nvIpam:
    image: nvidia-k8s-ipam
    repository: ghcr.io/mellanox
    version: |nvidia-ipam-version|
    imagePullSecrets: []
    enableWebhook: false
  secondaryNetwork:
    cniPlugins:
      image: plugins
      repository: ghcr.io/k8snetworkplumbingwg
      version: |cni-plugins-version|
    multus:
      image: multus-cni
      repository: ghcr.io/k8snetworkplumbingwg
      version: |multus-version| 