name: "Build"
on: [push, pull_request]

jobs:
  build:
    name: generate-html
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: ./repo.sh docs
      - name: 'upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: generated-html
          path: _build/docs/nvidia_network_operator
